/*
 * @Author: 成中锦
 * @Date: 2020-06-20 14:29:19
 * @LastEditTime: 2020-06-20 15:04:13
 * @FilePath: \wangyi_music\Api.js
 */ 
export default {
    "/login/cellphone":"手机登录",
    "/login":"邮箱登录-已失效",
    "/login/refresh":"登录信息刷新",
    "/banner":"banner-获取是老数据",
    "/playlist/catlist":"歌单类型列表",
    "/playlist/hot":"歌单类型列表-热门类型",
    "/personalized/newsong":"推荐新音乐",
    "/personalized":"推荐歌单",
    "/personalized/mv":"推荐mv",
    "/personalized/privatecontent":"独家放送",
    "/personalized/djprogram":"推荐dj",
    "/personalized/topic":"推荐dj",
    "/recommend/songs":"每日推荐歌曲",
    "/recommend/dislike":"取消推荐",
    "/recommend/resource":"每日推荐歌单",
    "/playlist/tracks":"收藏单曲到歌单，从歌单删除歌曲",    // op=del,add;pid=歌单id,tracks=歌曲id
    "/search":"搜索",
    "/search/multimatch":"搜索 multimatch",
    "/search/hot":"搜索 hot",
    "/search/suggest":"搜索 suggest",
    "/fm":"fm",
    "/lyric":"歌词",
    "/top/artist":"热门歌手",
    "/top/songs":"新歌上架",                                           // ,type ALL, ZH,EA,KR,JP
    "/top/album":"新碟上架",                                           // ,type ALL, ZH,EA,KR,JP
    "/top/mv":"mv",                                           // ,type ALL, ZH,EA,KR,JP
    "/top/mv/first":"最新mv",                                           // ,type ALL, ZH,EA,KR,JP
    "/top/playlist":"分类歌单",
    "/top/playlist/highquality":"精品歌单",
    "/simi/playlist":"相似歌单",
    "/simi/song":"相似歌曲",
    "/simi/user":"相似关注的用户",
    "/comments":"评论",
    "/artist":"艺术家",
    "/artist/sub":"关注歌手",
    "/artist/album":"艺术家-专辑",
    "/artist/mv":"艺术家-mv",
    "/artist/desc":"艺术家 信息",
    "/artist/simi":"艺术家 ,相似歌手",
    "/user/subcount":"云盘数据个人信息",
    "/user/cloud":"云盘数据歌单",
    "/user/cloud/search":"云盘数据收藏，mv,dj数量",
    "/mv":"mv detail",
    "/mv/simi":"simi mv",
    "/mv/url":"mv播放地址",
    "/music/detail":"单曲详情",
    "/album/detail":"专辑详情",
    "/music/url":"单曲播放地址",
    "/user/detail":"用户详情",
    "/user/playlist":"用户歌单",
    "/user/radio":"用户电台",
    "/user/follows":"用户关注列表",
    "/follow":"关注,取消关注，用户",
    "/user/followeds":"用户粉丝列表",
    "/playlist/detail":"歌单详情",
    "/playlist/img":"歌单详情-旧，获取封面",
    "/daily_signin":"签到",
    "/record":"听歌记录 uid,type 0所以，1 week，",
    "/likelist":"红心歌曲",
    "/like/album":"红心歌曲",
    "/program/like":"program-like",
    "/djradio/catelist":"电台类型列表",
    "/program/recommend":"推荐节目",
    "/djradio/recommend":"精选电台",
    "/djradio/recommend/type":"精选电台-分类电台",
    "/djradio/hot":"分类电台",
    "/program/detail":"dj单期节目program-detail",
    "/dj/program":"dj主播 radio",
    "/dj/detail":"djradio detail",
    "/event/get":"用户动态",
    "/event/list":"朋友",
    "/dj/sub":"dj 订阅",
    "/resource/like":"program like act",
    "/comment/like":"comment like act",
    "/song/tracks":"歌曲喜欢和删除 op=like or trash,songid,",
    "/user/dj":"用户电台",
    "/log/web":"xxxxxxx",
    "/id2url":"xxxxxxx",
    "/toplist":"toplist",
    "/playlist/all":"播放列表",
    "/toplist/detail":"排行榜详细",
    "/toplist/artist":"艺术家分类",
    "/sublist/artist":"我的收藏-歌手",
    "/sublist/album":"我的收藏-专辑",
    "/sublist/mv":"我的收藏-mv",
    "/sublist/radio":"我的收藏-歌手",
    "/sublist/topic":"我的收藏-专栏",
    "/video/playurl":"短视频-播放地址",
    "/video/detail":"短视频-detail",
    "/video/rcmd":"短视频-simi",
    "/video/statistic":"短视频-statistic",
    "/topic/detail":"topic detail",
    "/playlist/fav":"歌单收藏-取消收藏",
}